# -*- coding: utf-8 -*-
"""derin_öğrenme_proje.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hmlVd6mE39-21yCN7Yhkks-xfnM2rGCG
"""

# @title 1. Kütüphanelerin Kurulumu ve İçe Aktarılması



import pandas as pd
import numpy as np
import re
import nltk
import torch
import matplotlib.pyplot as plt
import seaborn as sns
from nltk.corpus import stopwords
from nltk.stem.snowball import SnowballStemmer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, ConfusionMatrixDisplay, classification_report
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer, DataCollatorWithPadding
import evaluate

nltk.download("stopwords")
print("Gerekli kütüphaneler kuruldu ve içe aktarıldı.")

# @title 2. Veri Yükleme (Google Drive - Herkese Açık Link)


FILE_ID = "1RgIS264M7ovdhzgeo_2kiDRH9s3tdleQ"
DOSYA_URLSI = f"https://drive.google.com/uc?export=download&id={FILE_ID}"

print(f"Veri seti indiriliyor: {DOSYA_URLSI}")

try:
    df = pd.read_csv(DOSYA_URLSI,
                     encoding='utf-16',
                     sep=',',
                     engine='python',
                     header=None,
                     names=['yorum', 'duygu'],
                     on_bad_lines='skip')


    df.columns = ['text', 'label']


    df = df[df['label'].isin(['Olumlu', 'Olumsuz'])]
    df['label'] = df['label'].map({'Olumlu': 1, 'Olumsuz': 0})

    print("Veri seti başarıyla yüklendi.")
    print(f"Toplam Kayıt Sayısı: {len(df)}")
    print(df.head())


    plt.figure(figsize=(6, 4))
    sns.countplot(x='label', data=df)
    plt.title('Sınıf Dağılımı (0: Olumsuz, 1: Olumlu)')
    plt.show()

except Exception as e:
    print(f"Hata oluştu: {e}")

# @title 3. Veri Ön İşleme

stop_words = set(stopwords.words("turkish"))
stemmer = SnowballStemmer("english")

def on_isleme(metin):

    metin = str(metin).lower()
    metin = re.sub(r'[^a-zA-ZçÇğĞıİöÖşŞüÜ\s]', '', metin)

    kelimeler = metin.split()
    kelimeler = [w for w in kelimeler if w not in stop_words]

    return " ".join(kelimeler)


df['clean_text'] = df['text'].apply(on_isleme)

print("Ön işleme sonrası örnek veri:")
print(df[['text', 'clean_text']].head())


X_train, X_test, y_train, y_test = train_test_split(df['clean_text'], df['label'], test_size=0.2, random_state=42)


from datasets import Dataset
train_dataset_raw = Dataset.from_dict({'text': X_train.tolist(), 'label': y_train.tolist()})
test_dataset_raw = Dataset.from_dict({'text': X_test.tolist(), 'label': y_test.tolist()})

# @title 4. Model Eğitimi ve Değerlendirme Altyapısı


accuracy_metric = evaluate.load("accuracy")
f1_metric = evaluate.load("f1")
precision_metric = evaluate.load("precision")
recall_metric = evaluate.load("recall")

def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    predictions = np.argmax(predictions, axis=1);

    acc = accuracy_metric.compute(predictions=predictions, references=labels)
    f1 = f1_metric.compute(predictions=predictions, references=labels)
    prec = precision_metric.compute(predictions=predictions, references=labels)
    rec = recall_metric.compute(predictions=predictions, references=labels)

    return {
        "accuracy": acc["accuracy"],
        "f1": f1["f1"],
        "precision": prec["precision"],
        "recall": rec["recall"]
    }


def train_transformer_model(model_name, train_ds, test_ds):
    print(f"\n===== {model_name} Modeli Hazırlanıyor =====")


    tokenizer = AutoTokenizer.from_pretrained(model_name)

    def tokenize_function(examples):
        return tokenizer(examples["text"], padding="max_length", truncation=True, max_length=128)

    tokenized_train = train_ds.map(tokenize_function, batched=True)
    tokenized_test = test_ds.map(tokenize_function, batched=True)


    model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=2)


    training_args = TrainingArguments(
        output_dir=f"./results_{model_name.replace('/', '_')}",
        learning_rate=2e-5,
        per_device_train_batch_size=16,
        per_device_eval_batch_size=16,
        num_train_epochs=1,
        weight_decay=0.01,
        eval_strategy="epoch",
        save_strategy="epoch",
        load_best_model_at_end=True,
        push_to_hub=False,
        report_to="none"
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=tokenized_train,
        eval_dataset=tokenized_test,
        tokenizer=tokenizer,
        data_collator=DataCollatorWithPadding(tokenizer=tokenizer),
        compute_metrics=compute_metrics,
    )

    print(f"{model_name} eğitiliyor...")
    trainer.train()

    print(f"{model_name} değerlendiriliyor...")
    eval_results = trainer.evaluate()


    predictions = trainer.predict(tokenized_test)
    preds = np.argmax(predictions.predictions, axis=1)

    return eval_results, preds, trainer

# @title 5. Modellerin Çalıştırılması (BERTurk ve XLM-RoBERTa)

# 1. Model: BERTurk (Türkçe için özel eğitilmiş)
model1_name = "dbmdz/bert-base-turkish-cased"
results_bert, preds_bert, trainer_bert = train_transformer_model(model1_name, train_dataset_raw, test_dataset_raw)

# 2. Model: XLM-RoBERTa (Çok dilli güçlü bir model)
model2_name = "xlm-roberta-base"
results_roberta, preds_roberta, trainer_roberta = train_transformer_model(model2_name, train_dataset_raw, test_dataset_raw)

# @title 6. Sonuçların Görselleştirilmesi ve Raporlama


comparison_df = pd.DataFrame([
    {"Model": "BERTurk", "Accuracy": results_bert['eval_accuracy'], "F1": results_bert['eval_f1'], "Precision": results_bert['eval_precision'], "Recall": results_bert['eval_recall']},
    {"Model": "XLM-RoBERTa", "Accuracy": results_roberta['eval_accuracy'], "F1": results_roberta['eval_f1'], "Precision": results_roberta['eval_precision'], "Recall": results_roberta['eval_recall']}
])

print("\n--- Model Performans Karşılaştırması ---")
print(comparison_df)


df_melted = comparison_df.melt(id_vars="Model", var_name="Metrik", value_name="Skor")

plt.figure(figsize=(10, 6))
sns.barplot(x="Metrik", y="Skor", hue="Model", data=df_melted, palette="viridis")
plt.title("Transformer Modellerinin Performans Karşılaştırması")
plt.ylim(0, 1.1)
plt.ylabel("Skor")
plt.legend(loc='lower right')
plt.show()


fig, axes = plt.subplots(1, 2, figsize=(14, 5))


cm_bert = confusion_matrix(y_test, preds_bert)
disp_bert = ConfusionMatrixDisplay(confusion_matrix=cm_bert, display_labels=['Olumsuz', 'Olumlu'])
disp_bert.plot(ax=axes[0], cmap='Blues')
axes[0].set_title(f'BERTurk Confusion Matrix\nAcc: {results_bert["eval_accuracy"]:.3f}')

cm_roberta = confusion_matrix(y_test, preds_roberta)
disp_roberta = ConfusionMatrixDisplay(confusion_matrix=cm_roberta, display_labels=['Olumsuz', 'Olumlu'])
disp_roberta.plot(ax=axes[1], cmap='Greens')
axes[1].set_title(f'XLM-RoBERTa Confusion Matrix\nAcc: {results_roberta["eval_accuracy"]:.3f}')

plt.show()

# @title 7. Gradio Arayüzü ile Tahmin
import gradio as gr
from transformers import pipeline

# En iyi performansı gösteren BERTurk modelini kullanacağız (trainer_bert)
# Modeli Gradio için uygun hale getirmek üzere bir pipeline oluşturuyoruz
# Not: Bu, Trainer nesnesini kullanmak yerine, modeli yükleyip pipeline oluşturmanın daha basit bir yoludur.
# Trainer'ın kendi .predict metodu, Gradio için uygun bir formatta çıktı vermez.

# Eğitilmiş BERTurk modelini yükle
model_name = "dbmdz/bert-base-turkish-cased"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model_for_inference = AutoModelForSequenceClassification.from_pretrained(trainer_bert.args.output_dir + "/checkpoint-425") # En iyi modeli yükle

# Duygu analizi için Transformer Pipeline oluşturma
# Bu, tahmin sürecini basitleştirir.
sentiment_pipeline = pipeline(
    "sentiment-analysis",
    model=model_for_inference,
    tokenizer=tokenizer,
    device=0 if torch.cuda.is_available() else -1  # GPU varsa 0, yoksa -1 (CPU) kullan
)

def predict_sentiment(text):
    """
    Kullanıcıdan alınan metin için duygu tahmini yapar.
    """
    # 1. Metni ön işlemeden geçir:
    clean_text = on_isleme(text)

    # 2. Modeli kullanarak tahmin yap:
    # Model 0: Olumsuz, 1: Olumlu olarak eğitildi.
    result = sentiment_pipeline(clean_text)[0]

    # 3. Sonucu daha okunaklı bir formata dönüştür:
    label_id = int(result['label'].split('_')[-1]) # LABEL_0 veya LABEL_1'den 0 veya 1'i alır

    if label_id == 1:
        sentiment = "Olumlu (Positive) 😊"
    else:
        sentiment = "Olumsuz (Negative) 😞"

    # Tahmin güven skorunu yüzde formatına dönüştürme
    score = result['score'] * 100

    return f"Tahmin: {sentiment}\nGüven Skoru: {score:.2f}%"

custom_css = """
.large-output-text textarea {
    font-size: 1.5em !important;
}
"""

# Gradio Arayüzünü Tanımlama
iface = gr.Interface(
    fn=predict_sentiment,
    inputs=gr.Textbox(lines=5, placeholder="Lütfen analiz etmek istediğiniz yorumu buraya girin...", label="Yorum Metni"),
    outputs=gr.Textbox(label="Duygu Analizi Sonucu", elem_classes=["large-output-text"]),
    title="BERTurk ile Türkçe Duygu Analizi",
    description="Eğitilmiş BERTurk modelini kullanarak girdiğiniz metnin duygu durumunu (Olumlu/Olumsuz) tahmin eder.",
    allow_flagging='never',
    css=custom_css,
    examples=examples
)
examples=[
        ["Ürün gerçekten çok kaliteli, bayıldım! Herkese tavsiye ederim."],     # Olumlu Örnek
        ["Kargo çok geç geldi ve paket özensizdi, hiç memnun kalmadım."],      # Olumsuz Örnek
        ["Tam bir fiyat performans ürünü, beklentimi karşıladı."],             # Olumlu Örnek
        ["Beklediğim gibi çıkmadı, kumaşı çok kalitesiz."],                    # Olumsuz Örnek
        ["Satıcı çok ilgiliydi, sorularıma hemen cevap verdi. Teşekkürler."]   # Olumlu Örnek
    ]
# Arayüzü Başlatma
# 'share=True' ile Gradio, arayüze herkesin erişebileceği geçici bir genel link oluşturur.
# Bu link Colab çıktı hücrenizde görünecektir.
print("\n--- Gradio Arayüzü Başlatılıyor ---")
iface.launch(share=True)